### ISSUE TITLE
Private package error

### ISSUE THREAD

**Issue by toumku** [Schmavery/drizzle-postgis#1]
I want to try this package. But is it private package or deleted?

When i try to `pnpm add drizzle-postgis`, below error occurs.

```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/drizzle-postgis: Not Found - 404

This error happened while installing a direct dependency of C:\code\orgs\hhyg\hilchin

drizzle-postgis is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]
```

**Comment by Schmavery** [comment]
@toumku sorry about this, I haven't gotten around to actually publishing the package yet 🤦 
I'll try to get to it soon, in the meantime, feel free to copy the *.ts files from https://github.com/Schmavery/drizzle-postgis/tree/main/src into your project?

Guess I was a little too optimistic when writing the README 😆

**Comment by Schmavery** [comment]
Ok this is now published. Please try again! :)

**Comment by dev-a-loper** [comment]
by the way It worth mentioning that npm supports direct links from github to be installed as packages 
I guess this will work :
```
npm install Schmavery/drizzle-postgis
```

**Comment by Schmavery** [comment]
did it work for you? wasn't sure if the typescript would be handled properly
